---

# Compile from git:
# git clone https://github.com/gsliepen/tinc && cd tinc/
# git checkout release-{{ tinc_version }}
# sudo apt-get install gcc autoconf make texinfo libncurses-dev libreadline-dev liblzo2-dev zlib1g-dev libssl-dev
# autoreconf -fis
# ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var
# make

- name: tinc VPN | remove default package
  tags:
  - package
  package:
    name: tinc
    state: absent

- name: tinc VPN | dependencies
  tags:
  - package
  package:
    name: "{{ item }}"
    state: latest
  with_items:
  - openssl
  - liblzo2-2
  notify: restart tinc

- name: tinc VPN | dhcpcd (OpenVZ)
  tags:
  - package
  apt:
    name: dhcpcd5
    install_recommends: no
  when: tinc_use_dhcpcd
  notify: restart tinc

- name: tinc VPN | disable resolvconf hook
  tags:
  - resolv
  lineinfile:
    path: /etc/dhcpcd.conf
    line: "nohook resolv.conf"
    create: yes
  when: tinc_use_dhcpcd

- name: tinc VPN | directory
  tags:
  - dir
  file:
    dest: "{{ tinc_dir }}/hosts"
    state: directory
  notify: restart tinc

- name: tinc VPN | binaries
  tags:
  - binary
  copy:
    src: "bin/{{ tinc_version }}/{{ ansible_architecture }}/{{ item }}"
    dest: /usr/sbin/
    mode: 0755
  with_items:
  - tinc
  - tincd
  notify: restart tinc

- name: tinc VPN | systemd unit files
  copy:
    src: "{{ item }}"
    dest: /lib/systemd/system/
  with_items:
  - tinc.service
  - tinc@.service
  notify: restart tinc

- name: tinc VPN | systemd-networkd config
  tags:
  - config
  template:
    src: vpn.network.j2
    dest: "/etc/systemd/network/20-{{ tinc_prefix }}{{ tinc_name }}.network"
  notify:
    - restart networkd
    - restart tinc

- name: tinc VPN | config
  tags:
  - config
  template:
    src: "{{ item }}.j2"
    dest: "{{ tinc_dir }}/{{ item }}"
    mode: 0700
  with_items:
  - tinc.conf
  - tinc-up
  - tinc-down
  notify: restart tinc

- name: tinc VPN | private key
  tags:
    - config
    - crypt
  copy:
    src: "{{ tinc_keydir }}/{{ item }}_key.priv"
    dest: "{{ tinc_dir }}"
    mode: 0400
  with_items: 
    - rsa
    - ed25519
  notify: restart tinc

- include_tasks: hostconf.yml
  vars:
    host: "{{ item }}"
  with_items: "{{ groups['vpn'] | union([inventory_hostname]) | unique }}"
  notify: restart tinc

- name: tinc VPN | service
  tags:
  - service
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
  - tinc
  - "tinc@{{ tinc_prefix }}{{ tinc_name }}"
