---
# Configure DHCP client (when can't use networkd's)

- name: dhcpcd | package
  tags:
    - package
  apt:
    name: dhcpcd5
    install_recommends: no
  notify: restart tinc

- name: dhcpcd | disable resolvconf hook
  tags:
    - resolv
  lineinfile:
    path: /etc/dhcpcd.conf
    line: "nohook resolv.conf"
    create: yes

- name: dhcpcd | disable service
  tags:
    - service
  service:
    name: dhcpcd
    state: stopped
    enabled: no

