---

- name: tinc VPN | iptables forward in
  tags:
    - iptables
  iptables:
    ip_version: "{{ item }}"
    chain: FORWARD
    in_interface: "{{ tinc_network }}"
    jump: ACCEPT
  loop: [ ipv4, ipv6 ]
  notify: iptables

- name: tinc VPN | iptables forward out
  tags:
    - iptables
  iptables:
    ip_version: "{{ item }}"
    chain: FORWARD
    out_interface: "{{ tinc_network }}"
    jump: ACCEPT
  loop: [ ipv4, ipv6 ]
  notify: iptables

- name: tinc VPN | iptables SNAT
  tags:
    - iptables
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: "{{ ansible_default_ipv4.interface }}"
    to_source: "{{ ansible_default_ipv4.address }}"
    jump: SNAT
  notify: iptables

- name: tinc VPN | iptables MASQUERADE
  tags:
    - iptables
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: "{{ tinc_network }}"
    jump: MASQUERADE
  notify: iptables

