---

- name: enable IP forwarding
  tags:
    - sysctl
  sysctl:
    name: net.ipv4.ip_forward
    value: 1

- name: tinc VPN | iptables forward in
  tags:
    - iptables
  iptables:
    ip_version: "{{ item }}"
    chain: FORWARD
    in_interface: "{{ tinc_prefix ~ tinc_network }}"
    jump: ACCEPT
  with_items: [ ipv4, ipv6 ]
  notify: iptables

- name: tinc VPN | iptables forward out
  tags:
    - iptables
  iptables:
    ip_version: "{{ item }}"
    chain: FORWARD
    out_interface: "{{ tinc_prefix ~ tinc_network }}"
    jump: ACCEPT
  with_items: [ ipv4, ipv6 ]
  notify: iptables

- name: tinc VPN | iptables SNAT
  tags:
    - iptables
  iptables:
    chain: POSTROUTING
    out_interface: "{{ tinc_prefix ~ tinc_network }}"
    to_source: "{{ ansible_default_ipv4.address }}"
    jump: SNAT
  notify: iptables

- name: tinc VPN | iptables MASQUERADE
  tags:
    - iptables
  iptables:
    chain: POSTROUTING
    out_interface: "{{ tinc_prefix ~ tinc_network }}"
    jump: MASQUERADE
  notify: iptables

