---

- name: tinc | host config
  tags:
    - config
    - crypt
  template:
    src: host.j2
    dest: "{{ tinc_dir }}/hosts/{{ hostvars[item]['tinc_nodename'] | default(item) }}"
    mode: 0640
  vars:
    tinc_addresses: "{{ hostvars[item]['tinc_addresses'] | default([]) }}"
    tinc_subnets:   "{{ hostvars[item]['tinc_subnets']   | default([]) }}"
    tinc_keydir:    "{{ tinc_keystore + '/' + item }}"
    tinc_ed25519:   "{{ lookup('file', tinc_keydir + '/ed25519_key.pub') }}"
    tinc_rsa:       "{{ lookup('file', tinc_keydir + '/rsa_key.pub'    ) }}"

