---
# Call this subroutine as:
# vars:
#   host: <inventory host>
# include_tasks: hostconf.yml

- name: tinc | host config
  tags:
  - config
  - crypt
  template:
    src: host.j2
    dest: "{{ tinc_dir }}/hosts/{{ tinc_name }}"
    mode: 0640
  vars:
    tinc_name     : "{{ hostvars[host]['tinc_name_'      ~ tinc_network] | d(hostvars[host].tinc_name     , true) | d(host, true) }}"
    tinc_addresses: "{{ hostvars[host]['tinc_addresses_' ~ tinc_network] | d(hostvars[host].tinc_addresses, true) | d([]  , true) }}"
    tinc_subnets  : "{{ hostvars[host]['tinc_subnets_'   ~ tinc_network] | d(hostvars[host].tinc_subnets  , true) | d([]  , true) }}"
    tinc_keydir:    "{{ tinc_keystore ~ '/' ~ host }}"
    tinc_ed25519:   "{{ lookup('file', tinc_keydir + '/ed25519_key.pub') }}"
    tinc_rsa:       "{{ lookup('file', tinc_keydir + '/rsa_key.pub'    ) }}"

