---

- name: tinc VPN | check for existing key
  local_action:
    module: stat
    path: "{{ tinc_keydir }}"
  register: keydir

- include_tasks: genkey.yml
  when: not keydir.stat.exists

- import_tasks: common.yml

- name: tinc VPN | client pubkeys
  block:
  - include_tasks: hostconf.yml
    loop: "{{ q('inventory_hostnames', tinc__nodes ~ '!' ~ tinc__servers) }}"
    loop_control:
      loop_var: host
  when: tinc__servers in group_names

- include_tasks: gateway.yml
  when: "'gw' in group_names"
