---

- name: tinc VPN | check for existing key
  local_action:
    module: stat
    path: "{{ tinc_keydir }}"
  register: keydir

- include_tasks: genkey.yml
  when: "not keydir.stat.exists and not 'vpn' in group_names"

- import_tasks: common.yml

- include_tasks: hostconf.yml
  vars:
    host: "{{ item }}"
  with_items: "{{ groups['all'] | difference(groups['vpn']) }}"
  when: "'vpn' in group_names"
