---

- name: tinc VPN | check for existing key
  local_action:
    module: stat
    path: "{{ tinc_keydir }}"
  register: keydir

- include_tasks: genkey.yml
  when: "not keydir.stat.exists"

- import_tasks: common.yml

- include_tasks: hostconf.yml
  with_inventory_hostnames: "{{ tinc_cur_nodes }}:!{{ tinc_cur_servers }}"
  when: "tinc_cur_servers in group_names"

- include_tasks: gateway.yml
  when: "'gw' in group_names"
