---

- name: tinc VPN | check for existing key
  local_action:
    module: stat
    path: "{{ tinc_keydir }}"
  register: keydir

- include_tasks: genkey.yml
  when: "not keydir.stat.exists"

- import_tasks: common.yml

- include_tasks: hostconf.yml
  with_inventory_hostnames: "{{ tinc__node_group }}:!{{ tinc__server_group }}"
  when: "tinc__server_group in group_names"
