---

- name: tinc VPN | check for existing key
  local_action:
    module: stat
    path: "{{ tinc_keydir }}"
  register: keydir

- include_tasks: genkey.yml
  when: not keydir.stat.exists

- import_tasks: common.yml

- include_tasks: dhcpcd.yml
  when: tinc_use_dhcpcd

- name: tinc VPN | client pubkeys
  block:
  - include_tasks: hostconf.yml
    loop: "{{ q('inventory_hostnames', 'tinc_nodes_' ~ tinc_network ~ ':!tinc_servers_' ~ tinc_network ) }}"
    loop_control:
      loop_var: host
  when: "'tinc_servers_' ~ tinc_network in group_names"

- include_tasks: gateway.yml
  when: "'gw' in group_names"
