---
- name: tinc | disable services
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  loop:
  - tinc
  - "tinc@{{ tinc_network }}"

- name: tinc | remove files
  file:
    path: "{{ item }}"
    state: absent
  loop:
  - /usr/sbin/tinc
  - /usr/sbin/tincd
  - "{{ tinc_dir }}"
  - "{{ tinc_iptables_conf | dirname }}"
  - "/etc/systemd/network/20-{{ tinc_network }}.network"
  - "/lib/systemd/system/tinc.service"
  - "/lib/systemd/system/tinc@.service"
