#! /system/bin/sh
## /data/local/busybox-links
## create softlinks for all busybox modules

bb=/data/magisk/busybox
target=/sbin

[ -x "$bb" ] || {
  echo "$0: missing busybox $bb"
  exit 1
}

for module in $("$bb" --list); do
  echo -n "$module "
  ln -s "$bb" "$target/$module"
done
echo
