---
- name: restart tinc
  tags:
  - service
  service:
    name: tinc
    state: restarted
    
- name: daemon-reload tinc
  tags:
    - systemd
  systemd:
    name: tinc
    state: restarted
    daemon-reload: yes
