#! /usr/bin/env ansible-playbook
# Remove tinc installation.
# Use '-l' to limit play to relevant hosts
---

- name: uninstall tinc VPN
  hosts: all
  tasks:
    - include_role:
        name: tinc
        tasks_from: uninstall.yml
      loop: "{{ vars.keys() | select('search', '^tinc_subnet_') | map('regex_replace', '^tinc_subnet_') | list }}"
      loop_control:
        loop_var: tinc_network
